PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?document vivo:dateTime ?dateTime .
} WHERE {
    <{{uri}}> tamu:CapstoneAdvisedOf ?document .
    ?document vivo:dateTimeValue ?dateTimeValue .
    ?dateTimeValue vivo:dateTime ?dateTime .
}
