PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?document rdfs:label ?label .
} WHERE {
    <{{uri}}> tamu:CapstoneAdvisedOf ?document .
    ?document rdfs:label ?label .
}
