PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?work vivo:dateTime ?publicationDate .
} WHERE {
    <{{uri}}> tamu:ETDChairOf ?work .
    ?work vivo:dateTimeValue ?dateTimeValue .
    ?dateTimeValue vivo:dateTime ?publicationDate .
}
