services:

  db:
    container_name: scholars-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=scholars
      - POSTGRES_USER=scholars
      - POSTGRES_PASSWORD=scholars
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  solr:
    container_name: scholars-solr
    image: solr:${SOLR_VERSION}
    environment:
      - SOLR_HOME=/var/solr/data
      - SOLR_HEAP=4g
      # Enable HTTP/2
      - SOLR_OPTS=-Dsolr.jetty.http2.enabled=true -Dsolr.jetty.h2c.enabled=true -Dsolr.jetty.http2.maxStreamTimeout=300000
    volumes:
      - ./solrdata:/var/solr/data
    ports:
      - 8983:8983
    command:
      - solr-precreate
      - scholars-discovery
