services:

  db:
    container_name: scholars-db
    image: postgres:${POSTGRES_VERSION}
    environment:
       - POSTGRES_DB=scholars
       - POSTGRES_USER=scholars
       - POSTGRES_PASSWORD=scholars
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  solr:
    container_name: scholars-solr
    image: solr:${SOLR_VERSION}
    environment:
      - SOLR_HOME=/var/solr/data
    volumes:
      - ./solrdata:/var/solr/data
      - ./managed-schema.xml:/opt/solr-${SOLR_VERSION}/server/solr/configsets/_default/conf/managed-schema.xml
    ports:
      - 8983:8983
    command:
      - solr-precreate
      - scholars-discovery
