ui:
  url: http://localhost:4200

discovery:
  ## copy a~n to src/main/resources/assets/a~n
  assets-location: classpath:/assets
  ## works in Windows and expected to work on Linux
  # assets-location: file:/Development/scholars/scholars-discovery/assets
  load-defaults: true
  update-defaults: true
  allowed-origins:
  - ${ui.url}
  auth:
    password:
      duration: 180
      min-length: 8
      max-length: 64
    token:
      server-integer: 1
      server-secret: wKFkxTX54UzKx6xCYnC8WlEI2wtOy0PR
      pseudo-random-number-bytes: 64
    registration-token-duration: 14
  mail:
    from: noreply@library.tamu.edu
    replyTo: helpdesk@library.tamu.edu
  http:
    connect-timeout: 5
    read-timeout: 30
  index:
    host: http://localhost:8983/solr
    operator: OR
    parser: edismax
    name: scholars-discovery
    cron: 0 0 0 * * SUN
    zone: America/Chicago
    schematize: false
    onStartup: false
    enableIndividualOnBatchFail: true
    onStartupDelay: 10000
    batchSize: 10000
  triplestore:
    type: edu.tamu.scholars.discovery.service.TdbTriplestore
    directory: triplestore
  harvesters:
  - type: edu.tamu.scholars.discovery.discovery.component.jena.TriplestoreHarvester
    documentTypes:
    - edu.tamu.scholars.discovery.discovery.model.Collection
    - edu.tamu.scholars.discovery.discovery.model.Concept
    - edu.tamu.scholars.discovery.discovery.model.Document
    - edu.tamu.scholars.discovery.discovery.model.Organization
    - edu.tamu.scholars.discovery.discovery.model.Person
    - edu.tamu.scholars.discovery.discovery.model.Process
    - edu.tamu.scholars.discovery.discovery.model.Relationship
  indexers:
  - type: edu.tamu.scholars.discovery.discovery.component.solr.SolrIndexer
    documentTypes:
    - edu.tamu.scholars.discovery.discovery.model.Collection
    - edu.tamu.scholars.discovery.discovery.model.Concept
    - edu.tamu.scholars.discovery.discovery.model.Document
    - edu.tamu.scholars.discovery.discovery.model.Organization
    - edu.tamu.scholars.discovery.discovery.model.Person
    - edu.tamu.scholars.discovery.discovery.model.Process
    - edu.tamu.scholars.discovery.discovery.model.Relationship
  export:
    individualKey: individual
    individualBaseUri: ${ui.url}/display

logging:
  file:
    name: logs/scholars.log
  level:
    edu:
      tamu:
        scholars:
          discovery: INFO
    org:
      springframework:
        security: INFO
        web: INFO

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  max-http-request-header-size: 16384
  port: 9001
  servlet:
    context-path:
  tomcat:
    connection-timeout: 900000

spring:
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
      max-page-size: 10000
    web:
      pageable:
        one-indexed-parameters: true
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
  messages:
    basename: i18n/messages
    cache-duration: 15
    encoding: UTF-8
  h2:
    console:
      enabled: false
      path: /h2console
  datasource:

    # h2
    # driver-class-name: org.h2.Driver

    # postgres
    driver-class-name: org.postgresql.Driver

    # h2 in memory
    # url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

    # h2 file
    # url: jdbc:h2:./h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

    # postgres
    url: jdbc:postgresql://localhost:5432/scholars

    username: scholars
    password: scholars
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        auto_close_session: true
        show_sql: false
    show-sql: false
  mail:
    host: smtp-relay.tamu.edu
  profiles:
    active: default
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  sql:
    init:
      platform: h2

management:
  endpoints:
    access:
      default: READ_ONLY
    web:
      exposure:
        # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
        include: health, info, index
  endpoint:
    health:
      access: READ_ONLY
      show-details: always
      show-components: always
    info:
      access: READ_ONLY
    index:
      access: READ_ONLY
