PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    ?startDate vivo:dateTimePrecision ?dateTimePrecision .
} WHERE {
    <{{uri}}> vivo:dateTimeInterval ?dateTimeInterval .
    ?dateTimeInterval vivo:start ?startDate .
    ?startDate vivo:dateTimePrecision ?dateTimePrecision .
}
