PREFIX tamu: <http://vivo.library.tamu.edu/ontology/TAMU#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
    <{{uri}}> tamu:awardConferredBy_label ?label .
} WHERE {
    <{{uri}}> tamu:awardConferredBy_label ?label .
    <{{uri}}> vivo:assignedBy ?assignedBy ; a vivo:AwardReceipt .
}
