name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        java-version: [17]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
        architecture: x64
        cache: 'maven'

    - name: Run Tests
      run: mvn clean test

    - name: Deploy to GitHub pages
      if: ${{ github.ref == 'refs/heads/tamu-main' && matrix.runs-on == 'ubuntu-latest' &&  matrix.java-version == '17' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/generated-docs
        branch: gh-pages
        clean: true
        single-commit: true
